# Generated by Django 5.1.2 on 2024-10-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=9)),
            ],
        ),
    ]
